GLOB sdist-make: /workdir/jmespath-1.0.1/setup.py
cpythonlibtest-unit-test-tests create: /workdir/jmespath-1.0.1/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest, -rrequirements.txt
cpythonlibtest-unit-test-tests inst: /workdir/jmespath-1.0.1/.tox/.tmp/package/1/jmespath-1.0.1.zip
cpythonlibtest-unit-test-tests installed: attrs==23.1.0,coverage==7.3.2,iniconfig==2.0.0,jmespath @ file:///workdir/jmespath-1.0.1/.tox/.tmp/package/1/jmespath-1.0.1.zip#sha256=a0720d456ca0b7b1c4ddc2bb34ef461bf4269b234df038648400f6a09fdceafb,mock==5.1.0,packaging==23.2,pluggy==1.3.0,py==1.11.0,pytest==6.2.5,pytest-cov==3.0.0,toml==0.10.2,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='2017666135'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/jmespath/1.0.1/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-6.2.5, py-1.11.0, pluggy-1.3.0 -- /workdir/jmespath-1.0.1/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/jmespath-1.0.1
plugins: cov-3.0.0
collecting ... collected 992 items / 1 error / 991 selected

==================================== ERRORS ====================================
__________________ ERROR collecting extra/test_hypothesis.py ___________________
ImportError while importing test module '/workdir/jmespath-1.0.1/extra/test_hypothesis.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
extra/test_hypothesis.py:8: in <module>
    from hypothesis import given, settings, assume, HealthCheck
E   ModuleNotFoundError: No module named 'hypothesis'
- generated xml file: /workdir/results/jmespath/1.0.1/1/cpython-test-results.xml -
=========================== short test summary info ============================
ERROR extra/test_hypothesis.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.23s ===============================
ERROR: InvocationError for command /workdir/jmespath-1.0.1/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/jmespath/1.0.1/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
