.package create: /workdir/preshed-3.0.8/.tox/.package
.package installdeps: setuptools, cython>=0.28, cymem>=2.0.2,<2.1.0, murmurhash>=0.28.0,<1.1.0
cpythonlibtest-unit-test-tests create: /workdir/preshed-3.0.8/.tox/cpythonlibtest-unit-test-tests
cpythonlibtest-unit-test-tests installdeps: mock, pytest, -rrequirements.txt
cpythonlibtest-unit-test-tests inst: /workdir/preshed-3.0.8/.tox/.tmp/package/1/preshed-3.0.8.tar.gz
cpythonlibtest-unit-test-tests installed: cymem==2.0.8,Cython==3.0.5,exceptiongroup==1.2.0,iniconfig==2.0.0,mock==5.1.0,murmurhash==1.0.10,packaging==23.2,pluggy==1.3.0,preshed @ file:///workdir/preshed-3.0.8/.tox/.tmp/package/1/preshed-3.0.8.tar.gz#sha256=99b4ef258f0aaf683c2b51094b6f7352509d0f1b87d492fb46ee307df87bdbc1,pytest==7.4.3,tomli==2.0.1
cpythonlibtest-unit-test-tests run-test-pre: PYTHONHASHSEED='901106264'
cpythonlibtest-unit-test-tests run-test: commands[0] | pytest -v --tb=native --junitxml /workdir/results/preshed/3.0.8/1/cpython-test-results.xml
============================= test session starts ==============================
platform linux -- Python 3.10.8, pytest-7.4.3, pluggy-1.3.0 -- /workdir/preshed-3.0.8/.tox/cpythonlibtest-unit-test-tests/bin/python
cachedir: .tox/cpythonlibtest-unit-test-tests/.pytest_cache
rootdir: /workdir/preshed-3.0.8
collecting ... collected 0 items / 4 errors

==================================== ERRORS ====================================
_________________ ERROR collecting preshed/tests/test_bloom.py _________________
ImportError while importing test module '/workdir/preshed-3.0.8/preshed/tests/test_bloom.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
preshed/tests/test_bloom.py:5: in <module>
    from preshed.bloom import BloomFilter
E   ModuleNotFoundError: No module named 'preshed.bloom'
________________ ERROR collecting preshed/tests/test_counter.py ________________
ImportError while importing test module '/workdir/preshed-3.0.8/preshed/tests/test_counter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
preshed/tests/test_counter.py:4: in <module>
    from preshed.counter import PreshCounter
E   ModuleNotFoundError: No module named 'preshed.counter'
________________ ERROR collecting preshed/tests/test_hashing.py ________________
ImportError while importing test module '/workdir/preshed-3.0.8/preshed/tests/test_hashing.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
preshed/tests/test_hashing.py:3: in <module>
    from preshed.maps import PreshMap
E   ModuleNotFoundError: No module named 'preshed.maps'
__________________ ERROR collecting preshed/tests/test_pop.py __________________
ImportError while importing test module '/workdir/preshed-3.0.8/preshed/tests/test_pop.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
preshed/tests/test_pop.py:1: in <module>
    from ..maps import PreshMap
E   ModuleNotFoundError: No module named 'preshed.maps'
- generated xml file: /workdir/results/preshed/3.0.8/1/cpython-test-results.xml -
=========================== short test summary info ============================
ERROR preshed/tests/test_bloom.py
ERROR preshed/tests/test_counter.py
ERROR preshed/tests/test_hashing.py
ERROR preshed/tests/test_pop.py
!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!
============================== 4 errors in 0.12s ===============================
ERROR: InvocationError for command /workdir/preshed-3.0.8/.tox/cpythonlibtest-unit-test-tests/bin/pytest -v --tb=native --junitxml /workdir/results/preshed/3.0.8/1/cpython-test-results.xml (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   cpythonlibtest-unit-test-tests: commands failed
