<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="183" failures="0" skipped="0" tests="183" time="18.762" timestamp="2023-11-20T21:32:29.638000" hostname="b80581c01e0f"><testcase classname="" name="tmp_rtrip.distutils.tests.test_archive_util" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_archive_util.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_bdist" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_bdist.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_bdist_dumb" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_bdist_dumb.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_bdist_msi" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_bdist_msi.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_bdist_rpm" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_bdist_rpm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_build" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_build.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_build_clib" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_build_clib.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_build_ext" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_build_ext.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_build_py" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_build_py.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_build_scripts" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_build_scripts.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_check" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_check.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_clean" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_clean.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_cmd" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_cmd.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_config" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_config.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_config_cmd" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_config_cmd.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_core" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_core.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_cygwinccompiler" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_cygwinccompiler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_dep_util" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_dep_util.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_dir_util" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_dir_util.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_dist" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_dist.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_extension" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_extension.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_file_util" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_file_util.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_filelist" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_filelist.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_install" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_install.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_install_data" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_install_data.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_install_headers" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_install_headers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_install_lib" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_install_lib.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_install_scripts" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_install_scripts.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_log" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_log.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_msvc9compiler" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_msvc9compiler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_msvccompiler" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_msvccompiler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_register" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_register.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_sdist" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_sdist.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_spawn" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_spawn.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_sysconfig" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_sysconfig.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_text_file" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_text_file.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_unixccompiler" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_unixccompiler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_upload" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_upload.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_util" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_util.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_version" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_version.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.distutils.tests.test_versionpredicate" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/distutils/tests/test_versionpredicate.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/distutils/tests/__init__.py:17: in &lt;module&gt;
    from test.support import run_unittest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_autocomplete" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_autocomplete.py", line 3, in &lt;module&gt;
    from unittest.mock import Mock, patch
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_autocomplete_w" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_autocomplete_w.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_autocomplete_w.py:3: in &lt;module&gt;
    from test.support import requires
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_autoexpand" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_autoexpand.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_autoexpand.py:4: in &lt;module&gt;
    from test.support import requires
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_browser" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_browser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_browser.py:2: in &lt;module&gt;
    from idlelib import browser
tmp_rtrip/idlelib/browser.py:13: in &lt;module&gt;
    from idlelib.config import idleConf
tmp_rtrip/idlelib/config.py:29: in &lt;module&gt;
    from tkinter.font import Font
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_calltip" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_calltip.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_calltip.py:2: in &lt;module&gt;
    from idlelib import calltip
tmp_rtrip/idlelib/calltip.py:13: in &lt;module&gt;
    from idlelib import calltip_w
tmp_rtrip/idlelib/calltip_w.py:6: in &lt;module&gt;
    from tkinter import Label, LEFT, SOLID, TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_calltip_w" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_calltip_w.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_calltip_w.py:2: in &lt;module&gt;
    from idlelib import calltip_w
tmp_rtrip/idlelib/calltip_w.py:6: in &lt;module&gt;
    from tkinter import Label, LEFT, SOLID, TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_codecontext" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_codecontext.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_codecontext.py:2: in &lt;module&gt;
    from idlelib import codecontext
tmp_rtrip/idlelib/codecontext.py:16: in &lt;module&gt;
    from tkinter import Frame, Text, TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_colorizer" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_colorizer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_colorizer.py:2: in &lt;module&gt;
    from idlelib import colorizer
tmp_rtrip/idlelib/colorizer.py:5: in &lt;module&gt;
    from idlelib.config import idleConf
tmp_rtrip/idlelib/config.py:29: in &lt;module&gt;
    from tkinter.font import Font
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_config" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_config.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_config.py:6: in &lt;module&gt;
    from idlelib import config
tmp_rtrip/idlelib/config.py:29: in &lt;module&gt;
    from tkinter.font import Font
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_config_key" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_config_key.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_config_key.py:7: in &lt;module&gt;
    from idlelib import config_key
tmp_rtrip/idlelib/config_key.py:4: in &lt;module&gt;
    from tkinter import Toplevel, Listbox, StringVar, TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_configdialog" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_configdialog.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_configdialog.py:5: in &lt;module&gt;
    from idlelib import configdialog
tmp_rtrip/idlelib/configdialog.py:13: in &lt;module&gt;
    from tkinter import Toplevel, Listbox, Canvas, StringVar, BooleanVar, IntVar, TRUE, FALSE, TOP, BOTTOM, RIGHT, LEFT, SOLID, GROOVE, NONE, BOTH, X, Y, W, E, EW, NS, NSEW, NW, HORIZONTAL, VERTICAL, ANCHOR, ACTIVE, END, TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_debugger" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_debugger.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_debugger.py:2: in &lt;module&gt;
    from idlelib import debugger
tmp_rtrip/idlelib/debugger.py:3: in &lt;module&gt;
    from tkinter import *
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_debugger_r" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_debugger_r.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_debugger_r.py:2: in &lt;module&gt;
    from idlelib import debugger_r
tmp_rtrip/idlelib/debugger_r.py:24: in &lt;module&gt;
    from idlelib import debugger
tmp_rtrip/idlelib/debugger.py:3: in &lt;module&gt;
    from tkinter import *
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_debugobj" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_debugobj.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_debugobj.py:2: in &lt;module&gt;
    from idlelib import debugobj
tmp_rtrip/idlelib/debugobj.py:2: in &lt;module&gt;
    from idlelib.tree import TreeItem, TreeNode, ScrolledCanvas
tmp_rtrip/idlelib/tree.py:2: in &lt;module&gt;
    from tkinter import *
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_editmenu" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_editmenu.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_editmenu.py:5: in &lt;module&gt;
    from test.support import requires
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_editor" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_editor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_editor.py:2: in &lt;module&gt;
    from idlelib import editor
tmp_rtrip/idlelib/editor.py:11: in &lt;module&gt;
    from tkinter import *
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_filelist" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_filelist.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_filelist.py:2: in &lt;module&gt;
    from idlelib import filelist
tmp_rtrip/idlelib/filelist.py:3: in &lt;module&gt;
    from tkinter import messagebox
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_format" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_format.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_format.py:2: in &lt;module&gt;
    from idlelib import format as ft
tmp_rtrip/idlelib/format.py:9: in &lt;module&gt;
    from tkinter.messagebox import askyesno
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_grep" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_grep.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_grep.py:8: in &lt;module&gt;
    from idlelib import grep
tmp_rtrip/idlelib/grep.py:9: in &lt;module&gt;
    from tkinter import StringVar, BooleanVar
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_help" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_help.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_help.py:2: in &lt;module&gt;
    from idlelib import help
tmp_rtrip/idlelib/help.py:30: in &lt;module&gt;
    from tkinter import Toplevel, Text, Menu
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_help_about" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_help_about.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_help_about.py:5: in &lt;module&gt;
    from idlelib import help_about
tmp_rtrip/idlelib/help_about.py:8: in &lt;module&gt;
    from tkinter import Toplevel, Frame, Label, Button, PhotoImage
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_history" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_history.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_history.py:2: in &lt;module&gt;
    from idlelib.history import History
tmp_rtrip/idlelib/history.py:2: in &lt;module&gt;
    from idlelib.config import idleConf
tmp_rtrip/idlelib/config.py:29: in &lt;module&gt;
    from tkinter.font import Font
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_hyperparser" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_hyperparser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_hyperparser.py:4: in &lt;module&gt;
    from test.support import requires
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_iomenu" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_iomenu.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_iomenu.py:2: in &lt;module&gt;
    from idlelib import iomenu
tmp_rtrip/idlelib/iomenu.py:7: in &lt;module&gt;
    from tkinter import filedialog
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_macosx" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_macosx.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_macosx.py:2: in &lt;module&gt;
    from idlelib import macosx
tmp_rtrip/idlelib/macosx.py:7: in &lt;module&gt;
    from test.support import requires, ResourceDenied
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_mainmenu" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_mainmenu.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_mainmenu.py:2: in &lt;module&gt;
    from idlelib import mainmenu
tmp_rtrip/idlelib/mainmenu.py:12: in &lt;module&gt;
    from idlelib.config import idleConf
tmp_rtrip/idlelib/config.py:29: in &lt;module&gt;
    from tkinter.font import Font
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_multicall" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_multicall.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_multicall.py:2: in &lt;module&gt;
    from idlelib import multicall
tmp_rtrip/idlelib/multicall.py:33: in &lt;module&gt;
    import tkinter
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_outwin" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_outwin.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_outwin.py:2: in &lt;module&gt;
    from idlelib import outwin
tmp_rtrip/idlelib/outwin.py:4: in &lt;module&gt;
    from tkinter import messagebox
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_parenmatch" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_parenmatch.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_parenmatch.py:6: in &lt;module&gt;
    from idlelib.parenmatch import ParenMatch
tmp_rtrip/idlelib/parenmatch.py:8: in &lt;module&gt;
    from idlelib.config import idleConf
tmp_rtrip/idlelib/config.py:29: in &lt;module&gt;
    from tkinter.font import Font
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_pathbrowser" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_pathbrowser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_pathbrowser.py:2: in &lt;module&gt;
    from idlelib import pathbrowser
tmp_rtrip/idlelib/pathbrowser.py:4: in &lt;module&gt;
    from idlelib.browser import ModuleBrowser, ModuleBrowserTreeItem
tmp_rtrip/idlelib/browser.py:13: in &lt;module&gt;
    from idlelib.config import idleConf
tmp_rtrip/idlelib/config.py:29: in &lt;module&gt;
    from tkinter.font import Font
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_percolator" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_percolator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_percolator.py:2: in &lt;module&gt;
    from idlelib.percolator import Percolator, Delegator
tmp_rtrip/idlelib/percolator.py:2: in &lt;module&gt;
    from idlelib.redirector import WidgetRedirector
tmp_rtrip/idlelib/redirector.py:1: in &lt;module&gt;
    from tkinter import TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_pyshell" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/tmp_rtrip/idlelib/pyshell.py", line 5, in &lt;module&gt;
    from tkinter import *
  File "/workdir/astor-0.8.1/tmp_rtrip/tkinter/__init__.py", line 35, in &lt;module&gt;
    import _tkinter
ModuleNotFoundError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_pyshell.py", line 2, in &lt;module&gt;
    from idlelib import pyshell
  File "/workdir/astor-0.8.1/tmp_rtrip/idlelib/pyshell.py", line 10, in &lt;module&gt;
    raise SystemExit(1)
SystemExit: 1</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_query" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_query.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_query.py:12: in &lt;module&gt;
    from idlelib import query
tmp_rtrip/idlelib/query.py:19: in &lt;module&gt;
    from tkinter import Toplevel, StringVar, BooleanVar, W, E, S
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_redirector" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_redirector.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_redirector.py:2: in &lt;module&gt;
    from idlelib.redirector import WidgetRedirector
tmp_rtrip/idlelib/redirector.py:1: in &lt;module&gt;
    from tkinter import TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_replace" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_replace.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_replace.py:2: in &lt;module&gt;
    from idlelib.replace import ReplaceDialog
tmp_rtrip/idlelib/replace.py:7: in &lt;module&gt;
    from tkinter import StringVar, TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_run" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_run.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_run.py:2: in &lt;module&gt;
    from idlelib import run
tmp_rtrip/idlelib/run.py:20: in &lt;module&gt;
    from idlelib import autocomplete
tmp_rtrip/idlelib/autocomplete.py:16: in &lt;module&gt;
    from idlelib import autocomplete_w
tmp_rtrip/idlelib/autocomplete_w.py:5: in &lt;module&gt;
    from tkinter import *
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_runscript" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_runscript.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_runscript.py:2: in &lt;module&gt;
    from idlelib import runscript
tmp_rtrip/idlelib/runscript.py:16: in &lt;module&gt;
    from tkinter import messagebox
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_scrolledlist" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_scrolledlist.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_scrolledlist.py:2: in &lt;module&gt;
    from idlelib.scrolledlist import ScrolledList
tmp_rtrip/idlelib/scrolledlist.py:1: in &lt;module&gt;
    from tkinter import *
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_search" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_search.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_search.py:2: in &lt;module&gt;
    from idlelib import search
tmp_rtrip/idlelib/search.py:7: in &lt;module&gt;
    from tkinter import TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_searchbase" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_searchbase.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_searchbase.py:3: in &lt;module&gt;
    from test.support import requires
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_searchengine" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_searchengine.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_searchengine.py:2: in &lt;module&gt;
    from idlelib import searchengine as se
tmp_rtrip/idlelib/searchengine.py:3: in &lt;module&gt;
    from tkinter import StringVar, BooleanVar, TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_sidebar" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_sidebar.py", line 6, in &lt;module&gt;
    import unittest.mock
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_squeezer" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_squeezer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_squeezer.py:3: in &lt;module&gt;
    from tkinter import Text, Tk
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_stackviewer" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_stackviewer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_stackviewer.py:2: in &lt;module&gt;
    from idlelib import stackviewer
tmp_rtrip/idlelib/stackviewer.py:4: in &lt;module&gt;
    import tkinter as tk
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_statusbar" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_statusbar.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_statusbar.py:2: in &lt;module&gt;
    from idlelib import statusbar
tmp_rtrip/idlelib/statusbar.py:1: in &lt;module&gt;
    from tkinter.ttk import Label, Frame
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_text" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_text.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_text.py:6: in &lt;module&gt;
    from test.support import requires
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_textview" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_textview.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_textview.py:8: in &lt;module&gt;
    from idlelib import textview as tv
tmp_rtrip/idlelib/textview.py:4: in &lt;module&gt;
    from tkinter import Toplevel, Text, TclError, HORIZONTAL, VERTICAL, NS, EW, NSEW, NONE, WORD, SUNKEN
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_tooltip" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_tooltip.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_tooltip.py:7: in &lt;module&gt;
    from idlelib.tooltip import TooltipBase, Hovertip
tmp_rtrip/idlelib/tooltip.py:7: in &lt;module&gt;
    from tkinter import *
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_tree" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_tree.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_tree.py:2: in &lt;module&gt;
    from idlelib import tree
tmp_rtrip/idlelib/tree.py:2: in &lt;module&gt;
    from tkinter import *
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_undo" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_undo.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_undo.py:4: in &lt;module&gt;
    from test.support import requires
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_warning" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_warning.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_warning.py:8: in &lt;module&gt;
    from idlelib import run
tmp_rtrip/idlelib/run.py:20: in &lt;module&gt;
    from idlelib import autocomplete
tmp_rtrip/idlelib/autocomplete.py:16: in &lt;module&gt;
    from idlelib import autocomplete_w
tmp_rtrip/idlelib/autocomplete_w.py:5: in &lt;module&gt;
    from tkinter import *
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_window" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_window.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_window.py:2: in &lt;module&gt;
    from idlelib import window
tmp_rtrip/idlelib/window.py:1: in &lt;module&gt;
    from tkinter import Toplevel, TclError
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_zoomheight" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_zoomheight.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_zoomheight.py:2: in &lt;module&gt;
    from idlelib import zoomheight
tmp_rtrip/idlelib/zoomheight.py:4: in &lt;module&gt;
    import tkinter
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.idlelib.idle_test.test_zzdummy" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/idlelib/idle_test/test_zzdummy.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/idlelib/idle_test/test_zzdummy.py:2: in &lt;module&gt;
    from idlelib import zzdummy
tmp_rtrip/idlelib/zzdummy.py:6: in &lt;module&gt;
    from idlelib.config import idleConf
tmp_rtrip/idlelib/config.py:29: in &lt;module&gt;
    from tkinter.font import Font
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.lib2to3.tests.test_all_fixers" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/lib2to3/tests/test_all_fixers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/lib2to3/tests/__init__.py:2: in &lt;module&gt;
    from test.support import load_package_tests
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.lib2to3.tests.test_fixers" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/lib2to3/tests/test_fixers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/lib2to3/tests/__init__.py:2: in &lt;module&gt;
    from test.support import load_package_tests
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.lib2to3.tests.test_main" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/lib2to3/tests/test_main.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/lib2to3/tests/__init__.py:2: in &lt;module&gt;
    from test.support import load_package_tests
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.lib2to3.tests.test_parser" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/lib2to3/tests/test_parser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/lib2to3/tests/__init__.py:2: in &lt;module&gt;
    from test.support import load_package_tests
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.lib2to3.tests.test_pytree" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/lib2to3/tests/test_pytree.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/lib2to3/tests/__init__.py:2: in &lt;module&gt;
    from test.support import load_package_tests
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.lib2to3.tests.test_refactor" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/lib2to3/tests/test_refactor.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/lib2to3/tests/__init__.py:2: in &lt;module&gt;
    from test.support import load_package_tests
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.lib2to3.tests.test_util" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/lib2to3/tests/test_util.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/lib2to3/tests/__init__.py:2: in &lt;module&gt;
    from test.support import load_package_tests
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test__opcode" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test__opcode.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test__opcode.py:2: in &lt;module&gt;
    from test.support.import_helper import import_module
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_asyncgen" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_asyncgen.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_asyncgen.py:5: in &lt;module&gt;
    from test.support.import_helper import import_module
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_base64" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_base64.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_base64.py:6: in &lt;module&gt;
    from test.support import os_helper
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_binhex" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_binhex.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_binhex.py:7: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_bufio" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_bufio.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_bufio.py:2: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_calendar" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_calendar.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_calendar.py:3: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_call" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_call.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_call.py:2: in &lt;module&gt;
    from test.support import cpython_only
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_code_module" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/test/test_code_module.py", line 6, in &lt;module&gt;
    from unittest import mock
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_codecencodings_tw" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_codecencodings_tw.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_codecencodings_tw.py:1: in &lt;module&gt;
    from test import multibytecodec_support
E   ImportError: cannot import name 'multibytecodec_support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_codecs" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/test/test_codecs.py", line 8, in &lt;module&gt;
    from unittest import mock
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_csv" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_csv.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_csv.py:9: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_ctypes" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_ctypes.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_ctypes.py:2: in &lt;module&gt;
    from test.support.import_helper import import_module
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_dataclasses" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/test/test_dataclasses.py", line 8, in &lt;module&gt;
    from unittest.mock import Mock
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_dbm" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_dbm.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_dbm.py:5: in &lt;module&gt;
    from test.support import import_helper
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_decorators" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_decorators.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_decorators.py:1: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_deque" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_deque.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_deque.py:3: in &lt;module&gt;
    from test import support, seq_tests
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_eof" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_eof.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_eof.py:3: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_faulthandler" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_faulthandler.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_faulthandler.py:9: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_fileinput" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_fileinput.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_fileinput.py:25: in &lt;module&gt;
    from test.support import verbose
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_genericpath" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_genericpath.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_genericpath.py:9: in &lt;module&gt;
    from test.support import os_helper
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_getargs2" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_getargs2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_getargs2.py:6: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_glob" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_glob.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_glob.py:6: in &lt;module&gt;
    from test.support.os_helper import TESTFN, skip_unless_symlink, can_symlink, create_empty_file, change_cwd
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_graphlib" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_graphlib.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_graphlib.py:5: in &lt;module&gt;
    from test.support.script_helper import assert_python_ok
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_hashlib" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_hashlib.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_hashlib.py:12: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_hmac" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/test/test_hmac.py", line 6, in &lt;module&gt;
    import unittest.mock
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_http_cookies" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_http_cookies.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_http_cookies.py:2: in &lt;module&gt;
    from test.support import run_unittest, run_doctest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_imghdr" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_imghdr.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_imghdr.py:7: in &lt;module&gt;
    from test.support import findfile
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_ipaddress" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_ipaddress.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_ipaddress.py:9: in &lt;module&gt;
    from test.support import LARGEST, SMALLEST
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_largefile" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_largefile.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_largefile.py:10: in &lt;module&gt;
    from test.support import requires, bigmemtest
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_lib2to3" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_lib2to3.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_lib2to3.py:2: in &lt;module&gt;
    from test.support.import_helper import import_fresh_module
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_linecache" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_linecache.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_linecache.py:7: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_mailbox" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_mailbox.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_mailbox.py:11: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_math" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_math.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_math.py:1: in &lt;module&gt;
    from test.support import run_unittest, verbose, requires_IEEE_754
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_minidom" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_minidom.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_minidom.py:4: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_multiprocessing_forkserver" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_multiprocessing_forkserver.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_multiprocessing_forkserver.py:2: in &lt;module&gt;
    import test._test_multiprocessing
E   ModuleNotFoundError: No module named 'test._test_multiprocessing'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_netrc" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_netrc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_netrc.py:2: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_plistlib" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_plistlib.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_plistlib.py:12: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_pwd" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_pwd.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_pwd.py:3: in &lt;module&gt;
    from test.support import import_helper
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_queue" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_queue.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_queue.py:7: in &lt;module&gt;
    from test.support import gc_collect
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_range" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_range.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_range.py:5: in &lt;module&gt;
    from test.support import ALWAYS_EQ
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_repl" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_repl.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_repl.py:7: in &lt;module&gt;
    from test.support import cpython_only, SuppressCrashReport
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_reprlib" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_reprlib.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_reprlib.py:11: in &lt;module&gt;
    from test.support import verbose
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_robotparser" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_robotparser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_robotparser.py:6: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_selectors" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_selectors.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_selectors.py:8: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_shlex" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/test/test_shlex.py", line 6, in &lt;module&gt;
    from unittest import mock
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_source_encoding" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_source_encoding.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_source_encoding.py:2: in &lt;module&gt;
    from test.support import script_helper, captured_stdout
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_spwd" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_spwd.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_spwd.py:3: in &lt;module&gt;
    from test.support import import_helper
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_stat" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_stat.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_stat.py:5: in &lt;module&gt;
    from test.support import os_helper
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_strftime" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_strftime.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_strftime.py:7: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_sundry" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_sundry.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_sundry.py:5: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_syntax" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_syntax.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_syntax.py:1313: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_sys_settrace" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_sys_settrace.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_sys_settrace.py:1: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_tarfile" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/test/test_tarfile.py", line 9, in &lt;module&gt;
    import unittest.mock
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_ttk_textonly" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_ttk_textonly.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_ttk_textonly.py:1: in &lt;module&gt;
    from test.support import import_helper
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_types" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_types.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_types.py:1: in &lt;module&gt;
    from test.support import run_with_locale, cpython_only
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_unicode" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_unicode.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_unicode.py:18: in &lt;module&gt;
    from test.support import import_helper
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_univnewlines" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_univnewlines.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_univnewlines.py:6: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_unparse" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_unparse.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_unparse.py:3: in &lt;module&gt;
    import test.support
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_urllib2" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_urllib2.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_urllib2.py:2: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_winconsoleio" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_winconsoleio.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_winconsoleio.py:8: in &lt;module&gt;
    from test.support import os_helper
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_winreg" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_winreg.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_winreg.py:3: in &lt;module&gt;
    from test.support import import_helper
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_wsgiref" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/test/test_wsgiref.py", line 1, in &lt;module&gt;
    from unittest import mock
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_xml_etree_c" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_xml_etree_c.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_xml_etree_c.py:3: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_yield_from" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_yield_from.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_yield_from.py:9: in &lt;module&gt;
    from test.support import captured_stderr, disable_gc, gc_collect
E   ModuleNotFoundError: No module named 'test.support'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_zipfile" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/test/test_zipfile.py", line 15, in &lt;module&gt;
    import unittest.mock as mock
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.test.test_zipfile64" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/test/test_zipfile64.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/test/test_zipfile64.py:1: in &lt;module&gt;
    from test import support
E   ImportError: cannot import name 'support' from 'test' (/workdir/astor-0.8.1/tmp_rtrip/test/__init__.py)</error></testcase><testcase classname="" name="tmp_rtrip.test.test_zipimport" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 531, in collect
    self._inject_setup_module_fixture()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 545, in _inject_setup_module_fixture
    self.obj, ("setUpModule", "setup_module")
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 310, in obj
    self._obj = obj = self._getobj()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 528, in _getobj
    return self._importtestmodule()
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/python.py", line 617, in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
  File "/workdir/astor-0.8.1/.tox/graalpylibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/opt/graalpy/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/workdir/astor-0.8.1/tmp_rtrip/test/test_zipimport.py", line 9, in &lt;module&gt;
    import unittest.mock
  File "/opt/graalpy/lib/python3.10/unittest/mock.py", line 26, in &lt;module&gt;
    import asyncio
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/__init__.py", line 3, in &lt;module&gt;
    from .base_events import *
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/base_events.py", line 39, in &lt;module&gt;
    from . import futures
  File "/workdir/astor-0.8.1/tmp_rtrip/asyncio/futures.py", line 380, in &lt;module&gt;
    Future = _CFuture = _asyncio.Future
AttributeError: module '_asyncio' has no attribute 'Future'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_colorchooser" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_colorchooser.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_font" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_font.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_geometry_managers" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_geometry_managers.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_images" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_images.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_loadtk" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_loadtk.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_messagebox" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_messagebox.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_misc" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_misc.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_simpledialog" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_simpledialog.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_text" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_text.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_variables" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_variables.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_tkinter.test_widgets" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_tkinter/test_widgets.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_ttk.test_extensions" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_ttk/test_extensions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_ttk.test_style" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_ttk/test_style.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase><testcase classname="" name="tmp_rtrip.tkinter.test.test_ttk.test_widgets" time="0.000"><error message="collection failure">ImportError while importing test module '/workdir/astor-0.8.1/tmp_rtrip/tkinter/test/test_ttk/test_widgets.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/opt/graalpy/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tmp_rtrip/tkinter/__init__.py:35: in &lt;module&gt;
    import _tkinter
E   ModuleNotFoundError: No module named '_tkinter'</error></testcase></testsuite></testsuites>