<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="4" failures="0" skipped="0" tests="4" time="0.182" timestamp="2023-11-30T05:36:09.365224" hostname="be2d8ee410eb"><testcase classname="" name="tests.main_test" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/tldextract-3.4.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/tldextract-3.4.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/tldextract-3.4.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/doctest.py", line 567, in collect
    module = import_path(
  File "/workdir/tldextract-3.4.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "&lt;frozen importlib._bootstrap&gt;", line 1050, in _gcd_import
  File "&lt;frozen importlib._bootstrap&gt;", line 1027, in _find_and_load
  File "&lt;frozen importlib._bootstrap&gt;", line 1006, in _find_and_load_unlocked
  File "&lt;frozen importlib._bootstrap&gt;", line 688, in _load_unlocked
  File "/workdir/tldextract-3.4.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/tldextract-3.4.0/tests/main_test.py", line 9, in &lt;module&gt;
    import responses
ModuleNotFoundError: No module named 'responses'</error><error message="collection failure">ImportError while importing test module '/workdir/tldextract-3.4.0/tests/main_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/main_test.py:9: in &lt;module&gt;
    import responses
E   ModuleNotFoundError: No module named 'responses'</error></testcase><testcase classname="" name="tests.test_parallel" time="0.000"><error message="collection failure">Traceback (most recent call last):
  File "/workdir/tldextract-3.4.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 341, in from_call
    result: Optional[TResult] = func()
  File "/workdir/tldextract-3.4.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/runner.py", line 372, in &lt;lambda&gt;
    call = CallInfo.from_call(lambda: list(collector.collect()), "collect")
  File "/workdir/tldextract-3.4.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/doctest.py", line 567, in collect
    module = import_path(
  File "/workdir/tldextract-3.4.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/pathlib.py", line 567, in import_path
    importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "&lt;frozen importlib._bootstrap&gt;", line 1050, in _gcd_import
  File "&lt;frozen importlib._bootstrap&gt;", line 1027, in _find_and_load
  File "&lt;frozen importlib._bootstrap&gt;", line 1006, in _find_and_load_unlocked
  File "&lt;frozen importlib._bootstrap&gt;", line 688, in _load_unlocked
  File "/workdir/tldextract-3.4.0/.tox/cpythonlibtest-unit-test-tests/lib/python3.10/site-packages/_pytest/assertion/rewrite.py", line 186, in exec_module
    exec(co, module.__dict__)
  File "/workdir/tldextract-3.4.0/tests/test_parallel.py", line 6, in &lt;module&gt;
    import responses
ModuleNotFoundError: No module named 'responses'</error><error message="collection failure">ImportError while importing test module '/workdir/tldextract-3.4.0/tests/test_parallel.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_parallel.py:6: in &lt;module&gt;
    import responses
E   ModuleNotFoundError: No module named 'responses'</error></testcase></testsuite></testsuites>